### PR TITLE
Add link to paper

### PR DESCRIPTION
**Pull request by tyleryasaka**
Peer-to-Peer Contact Tracing: Development of a Privacy-Preserving Smartphone App
http://doi.org/10.2196/18936

### CODE REVIEW

**Comment by shankari** [comment]
Looks cool! Are the checkpoints currently entered manually? It doesn't look like you have any sensing built into the app...

**Comment by tyleryasaka** [comment]
Thanks! Yes they are done manually. There are also "public checkpoints" which are QR codes that could be displayed at entrances to public places and quickly scanned with an ordinary smartphone camera (no app download or signup required, essentially takes 10 seconds).

My philosophy is to utilize social participation to drive adoption. Because it's a publicly visible and social activity, it's possible that this activity could become a social norm which would hopefully drive high adoption, as opposed to GPS- or Bluetooth-based methods which have no accountability (nobody will ever know if you're not participating).

**Comment by shankari** [comment]
I think that your point about social participation is well taken. Although, for the background sensed methods, you could have an "I'm COVID Aware" sticker on the phone, similar to "I voted" :)

**Comment by tyleryasaka** [comment]
True!

**Pull request merged**
