### PR TITLE
Add COVID Trace app

### PR DESCRIPTION
**Pull request by dudleycarr**

### CODE REVIEW

**Comment by shankari** [comment]
@dudleycarr your app looks cool, but I am not sure that it is a "Big project". @maxheld83 since you first started classifying the projects, can you let us know your opinion?

**Comment by dudleycarr** [comment]
@shankari I missed the disclaimer about "big projects." Our project doesn't have a lot of stars, yet. However, a number of the other projects have less activity or have fewer contributors. Just a thought.

**Comment by maxheld83** [comment]
sorry, I have no business being a gate keeper of any sort to these amazing and generous projects, and perhaps there shouldn't be any gatekeeper.

I just thought visitors to the site needed some sort of rough and dirty guidance on what were "big" projects, cause it's otherwise a bit overwhelming/frustrating.

@dudleycarr et al's project looks super professional, has lots of commits and collaborators, so I'd be happy to **boldface** it.

**Comment by shankari** [comment]
@maxheld83 I do think that some level of curation is a good idea to avoid overwhelming the reader. Thanks for the initial pass and for weighing in. Hopefully it will be easier to make these calls in the future.

**Pull request merged**
